# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-23 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceCheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecheckingsession',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
